# Generated by Django 3.0.5 on 2020-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='EC2 Instace unique ID', max_length=30)),
                ('role', models.CharField(help_text='EC2 Instace role label', max_length=10)),
            ],
        ),
    ]
